# Generated by Django 5.0.14 on 2026-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='行')),
                ('col', models.PositiveIntegerField(verbose_name='列')),
                ('occupant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('status', models.CharField(choices=[('empty', '空席'), ('occupied', '使用中')], default='empty', max_length=10, verbose_name='状態')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '座席',
                'verbose_name_plural': '座席',
                'ordering': ['row', 'col'],
                'unique_together': {('row', 'col')},
            },
        ),
    ]
